version: '3.8'

services:
  postgres:
    env_file: .env
    image: postgres:latest
    container_name: golang_postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DATABASE}
    volumes:
      - postgres:/data/postgres
    ports:
      - "5434:5432"
    restart: unless-stopped
volumes:
  postgres: